### ISSUE TITLE
Feature request: Misskey / Firefish Support

### ISSUE THREAD

**Issue by kazukyakayashi** [h3poteto/fedistar#1018]
A client that seems well done and interesting, but unfortunately does not support Misskey/Firefish (Calckey) instances.

But great work 👍

**Comment by h3poteto** [comment]
Memo:
- Notifications that do not have account field
- If a reaction has url/static_url field, we should use it for custom emoji reaction.

**Comment by yitsushi** [comment]
Tried on `master` and Misskey doesn't work :(

It still says:
> Failed to connect to slippy.xyz, make sure the server URL is valid or correct.

It downloads the body and find favicon, but can't identify. I see only Firefish is listed in the README now, but if Misskey is not supported, then please update the issue title and I'll create a new issue to support Misskey, I don't think it's resolved yet.

(i was so excited to see the issue is closed)

**Comment by h3poteto** [comment]
https://github.com/h3poteto/megalodon/issues/1669
I'm not going to support Misskey.

**Comment by yitsushi** [comment]
That's sad, thank you. Can you please update the issue title/description as it's a bit misleading that way (it indicated both of them were implemented), thank you.
