### ISSUE TITLE
Need to manually refresh timelines

### ISSUE THREAD

**Issue by hannessssss** [h3poteto/fedistar#1032]
First of all, thank you for this very promising client! I'm using it for Mastodon, displaying federated, local, home and notification timelines. Neither of them automatically streams updates, however. As per notes on previously closed issues, I assume this should be the case.

The log file is full of entries such as these (domain name and access token censored, but correct in original log):

```
2023-07-27T08:58:49.008917723Z [INFO] Reconnecting to wss://.../api/v1/streaming?stream=public&access_token=...
2023-07-27T08:58:49.143571628Z [ERROR] Failed to connect: HTTP error: 301 Moved Permanently
2023-07-27T08:58:52.725050784Z [INFO] Reconnecting to wss://.../api/v1/streaming?stream=public:local&access_token=...
2023-07-27T08:58:52.854691945Z [ERROR] Failed to connect: HTTP error: 301 Moved Permanently
2023-07-27T08:58:53.44682726Z [INFO] Reconnecting to wss://.../api/v1/streaming?stream=user&access_token=...
2023-07-27T08:58:53.601655365Z [ERROR] Failed to connect: HTTP error: 301 Moved Permanently
```

**Comment by h3poteto** [comment]
Hmm?? Your streaming URL is wrong, so it says 301.

**Comment by hannessssss** [comment]
Sure, it may be wrong. Though this raises two questions:

1. I never configured this URL, but the application somehow "guessed" it. There seems to be no way to configure/correct it. Is there a way for me to override it, keeping in mind that I don't know the correct one?
2. If the server sends a 301, why doesn't the application follow the redirect?

**Comment by h3poteto** [comment]
1. Yes, the application obtains websocket URL from `/api/v1/instance` endpoint. For example, https://mastodon.social/api/v1/instance You can see `wss://streaming.mastodon.social` in `urls.streaming_api`.
2. That's because it's not made that way. Basically, if a server returns the wrong streaming URL, it's a server side issue.

Can you tell me your server URL?

**Comment by frame** [comment]
It was indeed a problem with the server. In case someone else runs into this, the problem was a trailing slash in the vhost config in Apache.

`curl -I "https://dosgame.club/api/v1/streaming?streaming=public"`
vs.
`curl -I "https://dosgame.club/api/v1/streaming/?streaming=public"`

It appears some clients add the slash, some don't and then run into a redirect loop.

**Bad:**
```
ProxyPass /api/v1/streaming/ ws://localhost:4000/
ProxyPassReverse /api/v1/streaming/ ws://localhost:4000/
```

**Good:**
```
ProxyPass /api/v1/streaming ws://localhost:4000
ProxyPassReverse /api/v1/streaming ws://localhost:4000
```

Thanks for your help, @h3poteto. We found + fixed it thanks to your very good reply earlier.

**Comment by hannessssss** [comment]
Thank you both very much! I confirm it is working perfectly now!
