### ISSUE TITLE
Search accounts/tags/statuses

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/fedistar#23]
I'm thinking about where the search panel should be located.

- :-1:  Modal: Easy, but what happens when we click the tag or account? A new tag timeline is displayed?
- :-1:  Timeline: Search results are not a timeline. And I don't want to specify a server before creating a search tab.
- :+1: Sidebar like compose: Switch compose or search tab.

**Comment by GrahamDo** [comment]
My 2c: A search icon on the sidebar just below the New Post tab. Clicking it pops out a floating panel with a textbox. Type your query, hit ENTER, and it open the results in a new column. By default, it searches on the server your first active account is on... Or perhaps the last account you used to post. Or maybe there's a new setting to specify the default server to use for searches.

On the top of the search column (or maybe hidden behind the Column Settings button), there's a dropdown that lets you change the server on which this search is being performed (you can only pick between the servers that you've linked accounts for, obviously).

Most users won't care, since for all intents and purposes, it doesn't really matter which server you perform a search on because the search is always effectively across the entire fediverse.

What do you think?

**Comment by h3poteto** [comment]
> Clicking it pops out a floating panel with a textbox
> and it open the results in a new column

This is confusing. The results should be displayed near the search textbox.

> On the top of the search column (or maybe hidden behind the Column Settings button), there's a dropdown that lets you change the server on which this search is being performed

I agree, I will adopt this idea.

> Most users won't care, since for all intents and purposes, it doesn't really matter which server you perform a search on because the search is always effectively across the entire fediverse.

Hmm...... I understand what you say. However, it is hard to do this now. Because some results are duplicates when we search a word across all servers. For example, when I search the tag "#fedistar", both server "A" and server "B" have `#fedistar` tag. So multiple results for the same tag are displayed. But they are separate timelines (The tag timeline of `#fedsitar` in server "A" and the tag timeline of `#fesitar` in server "B" are different).

**Comment by GrahamDo** [comment]
> This is confusing. The results should be displayed near the search textbox.

You're right. It was me who was being confused. There's a difference between the search results and the hashtag/user you click. I'm trying to think of it in terms of how TweetDeck and Sengi (the Mastodon client I currently use) work. And you're right: you type your query in the textbox and hit ENTER, and the results appear just below the textbox.

So in fact, I guess, below the textbox, you could have a little dropdown or expandable thing that says, "Search using this server", and have it default as I described.

(Sengi's already got a concept of an "Active/Default Account". It's whatever profile picture you click on before you do anything. There's always one selected (and you'll identify it because it's glowing whereas all other accounts are dull) and everything, from searching to posting, happens in the context of that account. But I'm not a massive fan of that approach, so I think yours is actually much better)

Anyway, here's what Sengi's search panel looks like:

![image](https://user-images.githubusercontent.com/2564311/230275160-397669fa-8f2c-491a-a3df-46a259af3a63.png)

That's not a column: it expands out under the textbox as soon as I hit ENTER, and it floats above the right-most column. I can click the X in the top-right to close it. But if I click on the hashtag or the status or the user in those results, it will then open that hashtag or status or user in a new column.
